on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    tags:
      - "**"

name: "Run Mule Lint"

jobs:
  github-action:
    name: github-action
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git config user.email "mule-lint@github.com"
          git config user.name "GitHub Actions"
      - name: "Run action"
        uses: mule-lint/github-action@trunk
        with:
          rules-path: rules.txt
          dictionary-path: dictionary.txt
          source-directory: src/main/app
          output-file: output.json
      - uses: actions/upload-artifact@v2
        with:
          name: mule-lint-results
          path: output.json
